#!/usr/bin/env python3
"""Aggregates .workflow/events.jsonl per task and writes the table in
docs/workflow/metrics.md between the metrics:auto markers."""

import argparse
import bisect
import json
import re
import subprocess
from collections import Counter, defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / ".workflow" / "events.jsonl"
OUT = ROOT / "docs" / "workflow" / "metrics.md"
START = "<!-- metrics:auto:start -->"
END = "<!-- metrics:auto:end -->"
GAP_CAP_SECONDS = 15 * 60
UNTRACKED = "(untracked)"
SUBAGENT_TOOLS = {"Task", "Agent"}
# metrics.md is regenerated by this script, so it never counts as task work
PATHS = ["--", ".", ":(exclude)docs/workflow/metrics.md"]
HEADER = [
    "Task",
    "Active time",
    "Prompts",
    "Subagent runs",
    "Review rounds",
    "Stop blocks",
    "Tool calls",
    "Lines +/-",
    "Tests added",
    "ACs",
    "Tokens in",
    "Cache read",
    "Tokens out",
]
NEW_FILE = (
    "# Workflow metrics\n\n"
    "One row per task, generated by `scripts/workflow_metrics.py` from the local hook log.\n"
    "Tokens in is uncached input plus cache writes. Notes go outside the markers.\n\n"
)


@dataclass
class TaskMetrics:
    task_id: str
    active_seconds: float = 0
    prompts: int = 0
    subagent_runs: Counter = field(default_factory=Counter)
    stop_blocks: int = 0
    tool_calls: int = 0
    lines: tuple[int, int] | None = None  # added, removed
    tests_added: int | None = None
    acceptance_criteria: int | None = None
    tokens: tuple[int, int, int] | None = None  # in, cache read, out

    @property
    def review_rounds(self) -> int:
        return self.subagent_runs["reviewer"]


@dataclass
class Usage:
    ts: datetime | None
    tokens_in: int
    cache_read: int
    tokens_out: int


# --- aggregation (pure) ---


def parse_ts(value: object) -> datetime | None:
    try:
        ts = datetime.fromisoformat(str(value))
    except ValueError:
        return None
    return ts if ts.tzinfo else ts.replace(tzinfo=UTC)


def prepare(raw: Iterable[dict]) -> list[dict]:
    """Events sorted by time, with null task ids filled in where the session allows.

    A session that resolves to exactly one task gives that task to its null events
    (planning happens on main before the task record exists). Other null events
    are reported as untracked.
    """
    events = []
    for e in raw:
        ts = parse_ts(e.get("ts"))
        if ts is not None:
            events.append({**e, "ts": ts})
    events.sort(key=lambda e: e["ts"])

    session_tasks = defaultdict(set)
    for e in events:
        if e.get("session_id") and e.get("task_id"):
            session_tasks[e["session_id"]].add(e["task_id"])
    for e in events:
        if not e.get("task_id"):
            tasks = session_tasks.get(e.get("session_id"), set())
            e["task_id"] = next(iter(tasks)) if len(tasks) == 1 else UNTRACKED
    return events


def active_seconds(timestamps: list[datetime], cap: float = GAP_CAP_SECONDS) -> float:
    ordered = sorted(timestamps)
    return sum(
        min((b - a).total_seconds(), cap) for a, b in zip(ordered, ordered[1:], strict=False)
    )


def aggregate(events: list[dict]) -> dict[str, TaskMetrics]:
    """Per-task counts and active time from prepared events."""
    by_task = defaultdict(list)
    for e in events:
        by_task[e["task_id"]].append(e)

    metrics = {}
    for task_id, task_events in by_task.items():
        m = TaskMetrics(task_id, active_seconds=active_seconds([e["ts"] for e in task_events]))
        for e in task_events:
            if e.get("event") == "UserPromptSubmit":
                m.prompts += 1
            elif e.get("event") == "StopBlocked":
                m.stop_blocks += 1
            elif e.get("event") == "PreToolUse":
                m.tool_calls += 1
                if e.get("tool_name") in SUBAGENT_TOOLS and e.get("subagent_type"):
                    m.subagent_runs[e["subagent_type"]] += 1
        metrics[task_id] = m
    return metrics


def dedupe_usage(rows: Iterable[dict]) -> list[Usage]:
    """One Usage per assistant message. A message can span several transcript rows
    sharing message.id; the last row wins."""
    by_id = {}
    for row in rows:
        message = row.get("message")
        if row.get("type") != "assistant" or not isinstance(message, dict):
            continue
        usage = message.get("usage")
        if not isinstance(usage, dict) or not message.get("id"):
            continue
        by_id[message["id"]] = Usage(
            ts=parse_ts(row.get("timestamp")),
            tokens_in=(usage.get("input_tokens") or 0)
            + (usage.get("cache_creation_input_tokens") or 0),
            cache_read=usage.get("cache_read_input_tokens") or 0,
            tokens_out=usage.get("output_tokens") or 0,
        )
    return list(by_id.values())


def attribute_tokens(
    events: list[dict], usage_by_session: dict[str, list[Usage]]
) -> dict[str, tuple[int, int, int]]:
    """Each message's tokens go to the task of the latest event at or before it
    in the same session."""
    by_session = defaultdict(list)
    for e in events:
        by_session[e.get("session_id")].append(e)

    totals = defaultdict(lambda: [0, 0, 0])
    for session_id, usages in usage_by_session.items():
        session_events = by_session.get(session_id)
        if not session_events:
            continue
        times = [e["ts"] for e in session_events]
        for u in usages:
            i = bisect.bisect_right(times, u.ts) - 1 if u.ts else 0
            total = totals[session_events[max(i, 0)]["task_id"]]
            total[0] += u.tokens_in
            total[1] += u.cache_read
            total[2] += u.tokens_out
    return {task_id: tuple(t) for task_id, t in totals.items()}


def count_acceptance_criteria(record: str) -> int:
    m = re.search(r"^## Acceptance criteria\n(.*?)(?=^## |\Z)", record, re.M | re.S)
    return len(re.findall(r"^- \[[ xX]\]", m.group(1), re.M)) if m else 0


def parse_numstat(text: str) -> tuple[int, int]:
    added = removed = 0
    for line in text.splitlines():
        parts = line.split("\t")
        if len(parts) == 3 and parts[0].isdigit() and parts[1].isdigit():
            added += int(parts[0])
            removed += int(parts[1])
    return added, removed


def count_added_tests(patch: str) -> int:
    return len(re.findall(r"^\+\s*def test_", patch, re.M))


# --- rendering (pure) ---


def format_duration(seconds: float) -> str:
    minutes = round(seconds / 60)
    return f"{minutes // 60}h {minutes % 60:02d}m" if minutes >= 60 else f"{minutes}m"


def render_row(m: TaskMetrics) -> str:
    def opt(value: int | None) -> str:
        return "–" if value is None else f"{value:,}"

    runs = ", ".join(f"{name} {n}" for name, n in sorted(m.subagent_runs.items())) or "–"
    tokens = m.tokens or (None, None, None)
    cells = [
        m.task_id,
        format_duration(m.active_seconds),
        str(m.prompts),
        runs,
        str(m.review_rounds),
        str(m.stop_blocks),
        str(m.tool_calls),
        f"+{m.lines[0]} / -{m.lines[1]}" if m.lines else "–",
        opt(m.tests_added),
        opt(m.acceptance_criteria),
        *(opt(t) for t in tokens),
    ]
    return "| " + " | ".join(cells) + " |"


def existing_rows(block: str) -> dict[str, str]:
    """Data rows of a previously generated table, keyed by task id."""
    rows = {}
    for line in block.splitlines():
        if not line.startswith("|"):
            continue
        first = line.strip("|").split("|")[0].strip()
        if first and first != HEADER[0] and not set(first) <= set("-: "):
            rows[first] = line
    return rows


def render_table(metrics: dict[str, TaskMetrics], kept: dict[str, str]) -> str:
    """One row per task. Rows of tasks missing from the log are kept as they were."""
    rows = {**kept, **{task_id: render_row(m) for task_id, m in metrics.items()}}
    lines = [
        "| " + " | ".join(HEADER) + " |",
        "| " + " | ".join("---" for _ in HEADER) + " |",
        *(rows[task_id] for task_id in sorted(rows, key=lambda t: (t == UNTRACKED, t))),
    ]
    return "\n".join(lines)


def marked_block(text: str) -> tuple[int, int] | None:
    start = text.find(START)
    end = text.find(END, start)
    return (start + len(START), end) if start != -1 and end != -1 else None


def splice(text: str, table: str) -> str:
    """Replace what is between the markers, adding them at the end if missing."""
    span = marked_block(text)
    if span is None:
        prefix = text.rstrip("\n") + "\n\n" if text.strip() else NEW_FILE
        return f"{prefix}{START}\n{table}\n{END}\n"
    return f"{text[: span[0]]}\n{table}\n{text[span[1] :]}"


# --- I/O ---


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    try:
        with path.open() as f:
            for line in f:
                try:
                    row = json.loads(line)
                except ValueError:
                    continue
                if isinstance(row, dict):
                    rows.append(row)
    except OSError:
        pass
    return rows


def load_usage(events: list[dict]) -> dict[str, list[Usage]]:
    """Usage per session from its transcript and its subagents' transcripts."""
    transcripts = {}
    for e in events:
        if e.get("session_id") and e.get("transcript_path"):
            transcripts[e["session_id"]] = Path(e["transcript_path"])

    usage = {}
    for session_id, transcript in transcripts.items():
        rows = read_jsonl(transcript)
        for sub in sorted((transcript.with_suffix("") / "subagents").glob("*.jsonl")):
            rows += read_jsonl(sub)
        if found := dedupe_usage(rows):
            usage[session_id] = found
    return usage


def git(*args: str) -> str | None:
    try:
        r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    return r.stdout if r.returncode == 0 else None


def git_stats(task_id: str) -> tuple[tuple[int, int], int] | None:
    """(added, removed) and tests added: from the squash commit on main if there is
    one, otherwise from the task branch, including uncommitted work when it is the
    current branch."""
    sha = (git("log", "main", "-1", "--format=%H", f"--grep=^Task: {task_id}$") or "").strip()
    if sha:
        numstat = git("show", "--numstat", "--format=", sha, *PATHS)
        patch = git("show", "-U0", "--format=", sha, *PATHS)
        if numstat is None or patch is None:
            return None
        return parse_numstat(numstat), count_added_tests(patch)

    branches = (
        git("branch", "--list", f"task/{task_id}-*", "--format=%(refname:short)") or ""
    ).split()
    if not branches:
        return None
    branch = branches[0]
    base = (git("merge-base", "main", branch) or "").strip()
    if not base:
        return None
    on_branch = (git("branch", "--show-current") or "").strip() == branch
    target = [base] if on_branch else [base, branch]
    numstat = git("diff", "--numstat", *target, *PATHS)
    patch = git("diff", "-U0", *target, *PATHS)
    if numstat is None or patch is None:
        return None
    added, removed = parse_numstat(numstat)
    tests = count_added_tests(patch)
    if on_branch:
        for name in (git("ls-files", "--others", "--exclude-standard", *PATHS) or "").splitlines():
            try:
                text = (ROOT / name).read_text()
            except (OSError, UnicodeDecodeError):
                continue
            added += len(text.splitlines())
            tests += len(re.findall(r"^\s*def test_", text, re.M))
    return (added, removed), tests


def acceptance_criteria(task_id: str) -> int | None:
    records = sorted((ROOT / "docs" / "tasks").glob(f"{task_id}-*.md"))
    return count_acceptance_criteria(records[0].read_text()) if records else None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--log", type=Path, default=LOG, help="event log to read")
    parser.add_argument("--out", type=Path, default=OUT, help="Markdown file to update")
    args = parser.parse_args()

    events = prepare(read_jsonl(args.log))
    metrics = aggregate(events)
    tokens = attribute_tokens(events, load_usage(events))
    for task_id, m in metrics.items():
        m.tokens = tokens.get(task_id)
        if task_id == UNTRACKED:
            continue
        m.acceptance_criteria = acceptance_criteria(task_id)
        if stats := git_stats(task_id):
            m.lines, m.tests_added = stats

    text = args.out.read_text() if args.out.exists() else ""
    span = marked_block(text)
    kept = existing_rows(text[span[0] : span[1]]) if span else {}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(splice(text, render_table(metrics, kept)))
    print(f"{args.out}: {len(metrics)} task(s) from {len(events)} event(s)")


if __name__ == "__main__":
    main()
